# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: hx
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: cat
# Aliases allow you to create nicknames for gh commands
aliases:
  b: browse
  bf: '!open "$(gh browse --no-browser --commit=$(git rev-parse HEAD) $1)#$2"'
  co: pr checkout
  mrb: pr view --web
  prb: pr view --web
  prc: pr create --web
  ib: issue view --web
  issue-url: issue view --json url --jq .url
  brb:
    '!gh browse --branch $(git rev-parse --abbrev-ref --symbolic-full-name @{u}
    | sd "^[^/]*/" "" ) "$@"'
  project-items-with-status: "!gh project item-list --owner $(gh repo view --json owner --jq .owner.login) $1 --format json --jq '.items[] | select(.status == \"'\"$2\"'\") | .content.number'" 
  pr-merge-base: '!git merge-base ${1-HEAD} origin/$(gh pr view $2 --json baseRefName -q .baseRefName)'
  pr-merge-commit: pr view $1 --json mergeCommit,potentialMergeCommit -q '(.mergeCommit//.potentialMergeCommit).oid'
  pr-ref-name: pr view $1 --json headRefName -q .headRefName
  pr-ref: pr view $1 --json headRefOid -q .headRefOid
  pr-range: "pr view --json baseRefName,headRefName -q '\"origin/\"+.baseRefName+\"...origin/\"+.headRefName'"
  pr-unread-files: '!
    gh api graphql --paginate -F ''owner={owner}'' -F ''repo={repo}'' -f query=''query($endCursor: String, $owner: String!, $repo: String!) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: ''"${1-$(gh pr view --json number -q .number))}"'' {
          files(first: 100, after: $endCursor) {
            nodes { path viewerViewedState }
            pageInfo { hasNextPage endCursor }
          }
        }
      }
    }''|jq -r ''.data.repository.pullRequest.files.nodes|.[]|select(.viewerViewedState!="VIEWED")|.path'''
  repo-set-remote: '!gh repo set-default $(git remote get-url $1)'
  wfr: '!gh workflow run --ref $(git rev-parse --abbrev-ref --symbolic-full-name @{u} | sd "^[^/]*/" "") "$@"'
  wr: "!GH_RUN=\"$(gh run list --workflow=$1 -L1 --json databaseId,url --template '{{range .}}{{printf \"%.f\" .databaseId}}\n{{.url}}{{break}}{{end}}')\"; echo \"$GH_RUN\" | cut -d'\n' -f2; gh run watch $(echo \"$GH_RUN\" | cut -d'\n' -f1)"
  wfrw: '!gh wfr "$@" && sleep 3 && gh run list --workflow=$1 --limit=3 && sleep 3 && gh wr "$1"'
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
