# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: hx
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: cat
# Aliases allow you to create nicknames for gh commands
aliases:
  b: browse
  bf: '!open "$(gh browse --no-browser --commit=$(git rev-parse HEAD) $1)#$2"'
  co: pr checkout
  mrb: pr view --web
  prb: pr view --web
  prc: pr create --web
  ib: issue view --web
  issue-url: issue view --json url --jq .url
  brb:
    '!gh browse --branch $(git rev-parse --abbrev-ref --symbolic-full-name @{u}
    | sd "^[^/]*/" "" ) "$@"'
  project-items-with-status: "!gh project item-list --owner $(gh repo view --json owner --jq .owner.login) $1 --format json --jq '.items[] | select(.status == \"'\"$2\"'\") | .content.number'"
  pr-merge-base: '!git merge-base ${1-HEAD} origin/$(gh pr view $2 --json baseRefName -q .baseRefName)'
  pr-merge-commit: pr view $1 --json mergeCommit,potentialMergeCommit -q '(.mergeCommit//.potentialMergeCommit).oid'
  pr-ref-name: pr view $1 --json headRefName -q .headRefName
  pr-ref: pr view $1 --json headRefOid -q .headRefOid
  pr-range: "pr view --json baseRefName,headRefName -q '\"origin/\"+.baseRefName+\"...origin/\"+.headRefName'"
  pr-file-url: '!if [[ $# -gt 1 ]]; then n=$1; shift; fi; echo "$(gh pr view --json url --jq .url $n)/files#diff-$(printf %s $1 | shasum -a 256 | cut -d'' '' -f1)"'
  pr-file-browse: '!open $(gh pr-file-url $@)'
  pr-files-json: pr view --json files --jq .files
  pr-files-json-rest: '!gh api repos/tenthousandcoffees/api-server/pulls/$(gh pr view --json number -q .number)/files'
  pr-files-json-gql: '!
    gh api graphql --paginate -F ''owner={owner}'' -F ''repo={repo}'' -f query=''query($endCursor: String, $owner: String!, $repo: String!) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: ''"${1-$(gh pr view --json number -q .number))}"'' {
          files(first: 100, after: $endCursor) {
            nodes { additions changeType deletions path viewerViewedState }
            pageInfo { hasNextPage endCursor }
          }
        }
      }
    }''|jq -r ''.data.repository.pullRequest.files.nodes'''
  pr-file-viewed-gql: '!
    gh api graphql -F pr=$(gh pr view --json id --jq .id) -F path=$1 -f query=''mutation($pr: ID!, $path: String!) {
      markFileAsViewed(input: { pullRequestId: $pr, path: $path }) {
        pullRequest { number files { totalCount } }
      }
    }'''
  pr-file-unviewed-gql: '!
    gh api graphql -F pr=$(gh pr view --json id --jq .id) path=$1 -f query=''mutation($pr: ID!, $path: String!) {
      markFileAsUnviewed(input: { pullRequestId: $pr, path: $path }) {
        pullRequest { number files { totalCount } }
      }
    }'''
  pr-unread-files: '!gh pr-files-json-gql | jq -r ''.[]|select(.viewerViewedState!="VIEWED")|.path'''
  pr-unresolved-comments: '!
    if [[ $# -gt 1 ]]; then n=$1; shift; else n=$(gh pr view --json number --jq .number); fi;
    gh api graphql --paginate -F ''owner={owner}'' -F ''repo={repo}'' -F "pr=$n" "$@" -f query=''
      query($endCursor: String, $owner: String!, $repo: String!, $pr: Int!) {
        repository(owner: $owner, name: $repo) {
          pullRequest(number: $pr) {
            reviewThreads(first: 100, after: $endCursor) {
              edges { cursor node {
                isResolved
                line
                path
                comments(first: 100) {
                  nodes {
                    author { login ... on User { name } }
                    body
                    createdAt
                    isMinimized
                    url
                  }
                }
              }
            }}
          }
        }
      }'' | jq ''[.data.repository.pullRequest.reviewThreads.edges[] | (. + .node) | del(.node) | select(.isResolved | not) | .comments = (.comments.nodes | map(select(.isMinimized == false)))]''
    '
  pr-unresolved-comment:
  pr-files: 'pr diff --name-only'
  pr-id-gql: '!
    gh api graphql -F ''owner={owner}'' -F ''repo={repo}'' -f query=''query($owner: String!, $repo: String!) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: ''"${1-$(gh pr view --json number -q .number))}"'' {
          id
        }
      }
    }''|jq -r ''.data.repository.pullRequest.id'''
  pr-review-submit: '!
    if [[ $# -gt 1 ]]; then n=$1; shift; else n=$(gh pr view --json id --jq .id); fi;
    gh api graphql -F pr=$n -F action=$1 -f query=''mutation($pr: ID!, $action: PullRequestReviewEvent!) {
      submitPullRequestReview(input: { pullRequestId: $pr, event: $action }) {
        pullRequestReview { id comments { totalCount } }
      }
    }'''
  my-review-requests: 'pr list --search "sort:updated-desc user-review-requested:@me"'
  my-latest-review-request: 'pr list --search "sort:updated-desc user-review-requested:@me" --limit 1 --json number --jq .[].number'
  repo-set-remote: '!gh repo set-default $(git remote get-url $1)'
  wfr: '!gh workflow run --ref $(git rev-parse --abbrev-ref --symbolic-full-name @{u} | sd "^[^/]*/" "") "$@"'
  wr: "!GH_RUN=\"$(gh run list --workflow=$1 -L1 --json databaseId,url --template '{{range .}}{{printf \"%.f\" .databaseId}}\n{{.url}}{{break}}{{end}}')\"; echo \"$GH_RUN\" | cut -d'\n' -f2; gh run watch $(echo \"$GH_RUN\" | cut -d'\n' -f1)"
  wfrw: '!gh wfr "$@" && sleep 3 && gh run list --workflow=$1 --limit=3 && sleep 3 && gh wr "$1"'
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
