# yaml-language-server: $schema=config.schema.json
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: hx
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: cat
# Aliases allow you to create nicknames for gh commands
aliases:
  auth-current: auth status --json hosts --jq '.hosts."github.com".[] | select(.active) | .login'
  whoami: auth status --json hosts --jq '.hosts."github.com".[] | select(.active) | .login'
  auth-setup-gcm-local: |
    ! set -x
    remotename=${1:-origin};
    remoteurl=$(git config get --local "remote.$remotename.url");
    if [[ $remoteurl == *@* ]]; then
      exit 0;
    fi;
    ghuser=$(gh auth-current);
    while
      if permission=$(gh repo view $remoteurl --json viewerPermission --jq .viewerPermission) && [[ $permission = ADMIN ]]; then
        git config set --local "remote.$remotename.url" ${remoteurl%%//*}//$ghuser@${remoteurl#*//};
        break;
      fi;
      gh auth switch;
      [[ "$ghuser" != "$(gh auth-current)" ]];
    do :; done
  b: browse
  bf: '!open "$(gh browse --no-browser --commit=$(git rev-parse HEAD) $1)#$2"'
  br: branch
  co: pr checkout
  copilot-generate-commit-message-body: |
    !
    index=0
    for arg in $@; do ((index++)); if [[ $arg == -- ]]; then break; fi; done
    DIFF_COMMAND=(${@:0:$index})
    shift $index
    (
      for f in "$@"; do
        printf '%s\0%s\n' "${f}" "$(git "${DIFF_COMMAND[@]}" --patch --no-prefix "$f" | base64 -w0)"
      done
    ) | jq --raw-input --slurp --compact-output '. | rtrimstr("\n") | if . == "" then halt_error(1) else {
      messages: [{
        role: "user",
        content: "Use conventional commits format",
        copilot_references:(
          . | split("\n") | map(
            split("\u0000") |
            {type:"github.diff-hunk",data:{type:"diff-hunk","changeReference":"",headerContext:"",fileName: .[0],diff:.[1]|@base64d}}
          )
        ),
      }],
      temperature: 0.3,
      response_format: {
        type: "json_schema",
        json_schema: {
          description: "The schema to abide by when generating commit message output",
          name: "commit_message_response",
          strict: true,
          schema: {
            type: "object",
            properties: {
              title: { type: "string", description: "The commit message title/summary" },
              description: { type: "string", description: "The commit message description/body" }
            },
            required: ["title", "description"],
            additionalProperties: false
          }
        }
      }
    } end'
  copilot-generate-commit-message: |
    !
    set -eo pipefail
    OPTS_SPEC="\
    gh copilot-generate-commit-message [<options>] <args>...
    --
    h,help      show the help
    c,commit=    generate commit message for given commit
    "
    eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt --stuck-long -- "$@" || echo exit $?)"
    DIFF_COMMAND=(diff-index --cached HEAD)
    index=0
    for arg in $@; do
      index=$((index+1))
      case "$arg" in
        --commit=*) COMMIT="${arg#--commit=}"; DIFF_COMMAND=(diff-tree -r $COMMIT^ $COMMIT) ;;
        --) break; ;;
      esac
    done
    shift $index

    CHANGED_FILES=($(git "${DIFF_COMMAND[@]}" --name-only))
    if [[ ${#CHANGED_FILES} -eq 0 ]]; then
      echo "no files staged / changed" >&2
      exit 1
    fi
    # brew install loteoo/formulas/ks
    # save bearer via `ks -k login add gh-copilot-bearer-token`
    # TODO: mint tokens with `github.com/github-copilot/chat/token` endpoint. json result: `{ token: string, expiration: string, ssoOrgIds?: string[]}`
    GH_COPILOT_BEARER_TOKEN=$(ks -k login show gh-copilot-bearer-token)
    curl -s 'https://api.individual.githubcopilot.com/agents/github-commit-message-generation' \
        -X POST \
        -H "Authorization: GitHub-Bearer $GH_COPILOT_BEARER_TOKEN" \
        -H 'copilot-integration-id: commit-msg-gen' \
        -H 'Content-Type: text/event-stream' \
        --data-raw "$(gh copilot-generate-commit-message-body "${DIFF_COMMAND[@]}" -- "${CHANGED_FILES[@]}")" |
      rg '^data: *' --replace '' |
      rg -v --fixed-strings '[DONE]' |
      jq -r '.choices[0].message.content | fromjson | .title + (if .description == "" then "" else "\n\n" + .description end)'
  mrb: pr view --web
  prb: pr view --web
  prc: pr create --web
  ib: issue view --web
  issue-url: issue view --json url --jq .url
  brb: '!gh browse --branch $(git rev-parse --abbrev-ref --symbolic-full-name @{u} | sd "^[^/]*/" "" ) "$@"'
  generated-patterns: "!rg ' linguist-generated(=true)?' .gitattributes --replace= --no-line-number"
  project-items-with-status: "!gh project item-list --owner $(gh repo view --json owner --jq .owner.login) $1 --format json --jq '.items[] | select(.status == \"'\"$2\"'\") | .content.number'"
  pr-merge-base: '!git merge-base ${1-HEAD} origin/$(gh pr view $2 --json baseRefName -q .baseRefName)'
  pr-merge-commit: pr view $1 --json mergeCommit,potentialMergeCommit -q '(.mergeCommit//.potentialMergeCommit).oid'
  pr-ref-name: pr view $1 --json headRefName -q .headRefName
  pr-ref: pr view $1 --json headRefOid -q .headRefOid
  pr-range: "pr view --json baseRefName,headRefName -q '\"origin/\"+.baseRefName+\"...origin/\"+.headRefName'"
  pr-number: "!REF=${1-HEAD}; shift; BRANCH=$(git rev-parse --symbolic-full-name $REF); gh pr list --limit 1 --head ${BRANCH#refs/heads/} --json number --jq '.[].number' \"$@\""
  pfh: "!open $(gh pr-file-url $1)\"$2\""
  pr-file-url: '!if [[ $# -gt 1 ]]; then n=$1; shift; fi; echo "$(gh pr view --json url --jq .url ${n-$GH_PR})/files#diff-$(printf %s $1 | shasum -a 256 | cut -d'' '' -f1)"'
  pr-file-browse: '!open $(gh pr-file-url $@)'
  pr-files-json: pr view --json files --jq .files
  pr-files-json-rest: '!gh api repos/tenthousandcoffees/api-server/pulls/$(gh pr view --json number -q .number)/files'
  pr-files-json-gql-raw: |
    !
    PR="${1-${GH_PR-$(gh pr view --json number -q .number)}}"
    gh api graphql --paginate -F 'owner={owner}' -F 'repo={repo}' -F "pr=$PR" -f query='
    query($endCursor: String, $owner: String!, $repo: String!, $pr: Int!) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: $pr) {
          number files(first: 100, after: $endCursor) {
            nodes { additions changeType deletions path viewerViewedState }
            pageInfo { hasNextPage endCursor }
          }
        }
      }
    }'
  pr-files-json-gql: '! gh pr-files-json-gql-raw $@ | jq -r .data.repository.pullRequest.files.nodes'
  pr-file-viewed-gql: |
    !
    [[ $# -gt 1 && $2 != -* ]] && GH_PR=$1 && shift
    PR_ID=$(gh pr view $GH_PR --json id --jq .id) || exit $?
    FILEPATH="$1"; shift;
    gh api graphql -F pr=$PR_ID -F path=$FILEPATH -f query='
      mutation($pr: ID!, $path: String!) {
        markFileAsViewed(input: { pullRequestId: $pr, path: $path }) {
          pullRequest { number files(first: 100) { totalCount nodes { path viewerViewedState } } }
        }
      }' "$@"
  pr-file-viewed: |
    ! gh pr-file-viewed-gql "$1" --jq '
        .data.markFileAsViewed.pullRequest |
        ("#" + (.number | tostring) + " " +
          (.files.nodes | map(select(.viewerViewedState == "VIEWED")) | length | tostring) + "/" +
          (.files.totalCount | tostring)
        )
      '
  pr-file-unviewed-gql: |
    !
    [[ $# -gt 1 && $2 != -* ]] && GH_PR=$1 && shift
    PR_ID=$(gh pr view $GH_PR --json id --jq .id) || exit $?
    FILEPATH="$1"; shift;
    gh api graphql -F pr=$PR_ID -F path=$FILEPATH -f query='
      mutation($pr: ID!, $path: String!) {
        unmarkFileAsViewed(input: { pullRequestId: $pr, path: $path }) {
          pullRequest { number files(first: 100) { totalCount nodes { path viewerViewedState } } }
        }
      }' "$@"
  pr-file-unviewed: |
    ! gh pr-file-unviewed-gql "$1" --jq '
        .data.unmarkFileAsViewed.pullRequest |
        ("#" + (.number | tostring) + " " +
          (.files.nodes | map(select(.viewerViewedState == "VIEWED")) | length | tostring) + "/" +
          (.files.totalCount | tostring)
        )
      '
  pr-unread-files: '!gh pr-files-json-gql $1 | jq -r ''.[]|select(.viewerViewedState!="VIEWED")|.path'''
  pr-unresolved-comments: '!gh pr-unresolved-comments-gql "$@" | gh pr-review-comments-format'
  pr-unresolved-comments-file: '!gh pr-unresolved-comments-gql --file "$@" | gh pr-review-comments-format'
  pr-unresolved-comments-files: '!gh pr-unresolved-comments-gql "$@" | jq -r ''.[]|.path'' | uniq'
  pr-review-comments-format: |
    !
    jq -r '.[] | @base64' | while read -r thread; do
      id=$(         jq -nr --arg input $thread '$input | @base64d | fromjson | .id');
      path=$(       jq -nr --arg input $thread '$input | @base64d | fromjson | .path');
      startLine=$(  jq -nr --arg input $thread '$input | @base64d | fromjson | .startLine');
      line=$(       jq -nr --arg input $thread '$input | @base64d | fromjson | .line');
      subjectType=$(jq -nr --arg input $thread '$input | @base64d | fromjson | .subjectType');
      if [[ -f "$path" ]] ; then
        echo "";
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━";
        header="$path (outdated)"
        if [[ $subjectType = "FILE" ]]; then
          header="$path (file)";
        elif [[ -n "$line" ]] && [[ "$line" != "null" ]]; then
          header="$path:$line";
        fi;
        printf "%s \e[2m%s\e[22m\n" "$header" "$id";
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━";
        if [[ $subjectType != "FILE" ]] && [[ -n "$line" ]] && [[ "$line" != "null" ]]; then
          highlightLine="$line"
          if [[ -n "$startLine" ]] && [[ "$startLine" != "null" ]]; then
            highlightLine="$startLine:$line"
            start=$((startLine - 5));
          else
            start=$((line - 5));
          fi
          if [[ start -lt 1 ]]; then start=1; fi;
          end=$((line + 5));
          bat --no-pager --style=numbers --color=always --highlight-line="$highlightLine" --line-range="$start:$end" "$path" 2>/dev/null;
        fi;
      else
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━";
      fi;
      echo "$thread" | base64 -d | jq -r '.comments[] | @base64' | while read -r comment; do
        author=$(  jq -nr --arg input $comment '$input | @base64d | fromjson | .author.login');
        body=$(    jq -nr --arg input $comment '$input | @base64d | fromjson | .body');
        utc_date=$(jq -nr --arg input $comment '$input | @base64d | fromjson | .publishedAt');
        url=$(     jq -nr --arg input $comment '$input | @base64d | fromjson | .url');
        id=$(      jq -nr --arg input $comment '$input | @base64d | fromjson | .id');
        local_date=$(date -j -f "%Y-%m-%dT%H:%M:%SZ" "$utc_date" "+%Y-%m-%d %H:%M:%S %Z" 2>/dev/null || date -d "$utc_date" "+%Y-%m-%d %H:%M:%S %Z" 2>/dev/null || echo "$utc_date");
        echo "";
        printf "@%s (\e]8;;%s\e\\%s\e]8;;\e\\): \e[2m%s\e[22m\n" "$author" "$url" "$local_date" "$id";
        echo "$body" | mcat --no-linenumbers --paging=never;
      done;
      echo "";
    done
  pr-unresolved-comments-first: '!gh pr-unresolved-comments-gql "$@" | jq -r ''nth(0) | .path + " +" + (.line|tostring)'''
  pr-review-comments-gql-raw: |
    ! [[ $# -gt 0 ]] && GH_PR=$1 && shift
    [[ -n "$GH_PR" ]] || GH_PR=$(gh pr view --json number --jq .number) || exit $?
    gh api graphql --paginate -F 'owner={owner}' -F 'repo={repo}' -F "pr=$GH_PR" "$@" -f query='
      query($endCursor: String, $owner: String!, $repo: String!, $pr: Int!) {
        repository(owner: $owner, name: $repo) {
          pullRequest(number: $pr) {
            reviewThreads(first: 100, after: $endCursor) {
              edges { cursor node {
                id isResolved line startLine originalLine originalStartLine path subjectType
                comments(first: 100) { nodes {
                  id
                  author { login ... on User { name } }
                  body createdAt isMinimized publishedAt url
                }}
              }
            }}
          }
        }
      }'
  pr-review-comments-gql: |
    ! gh pr-review-comments-gql-raw "$@" |
      jq '[ .data.repository.pullRequest.reviewThreads.edges[] | (. + .node) | del(.node) ]'
  pr-unresolved-comments-gql: |
    !
    nodeconditions=""
    conditions=""
    while true; do
      case "$1" in
        --not) conditions+=" and .id != \"$2\""; shift 2; ;;
        --file) nodeconditions+=" and .path == \"$2\""; shift 2; ;;
        --reviewer) nodeconditions+=" and .comments[0].author.login == \"$2\""; shift 2; ;;
        *) break; ;;
      esac
    done
    gh pr-review-comments-gql-raw "$@" |
      jq "[ .data.repository.pullRequest.reviewThreads.edges[] |
            (. + .node) | del(.node) |
            .comments = (.comments.nodes | map(select(.isMinimized == false $conditions))) |
            select((.isResolved | not) $nodeconditions $conditions)
          ]"
  pr-files: 'pr diff --name-only'
  pr-id-gql: |
    ! [[ $# -gt 0 && $1 != -*  ]] && GH_PR=$1 && shift
      [[ -n "$GH_PR" ]] || GH_PR=$(gh pr view --json number --jq .number) || exit $?
      gh api graphql -F 'owner={owner}' -F 'repo={repo}' -F "pr=$GH_PR"  -f query='
      query($owner: String!, $repo: String!, $pr: Int!) {
        repository(owner: $owner, name: $repo) { pullRequest(number: $pr) { id } }
      }' | jq -r '.data.repository.pullRequest.id'
  pr-review-submit: |
    ! [[ $# -gt 1 && $1 =~ "\d+" ]] && GH_PR=$1 && shift
    PR_ID=$(gh pr view $GH_PR --json id --jq .id) || exit $?
    gh api graphql -F pr=$PR_ID -F action="$1" -F body="$2" -f query='mutation($pr: ID!, $action: PullRequestReviewEvent!, $body: String) {
      submitPullRequestReview(input: { pullRequestId: $pr, event: $action, body: $body }) {
        pullRequestReview { id comments { totalCount } }
      }
    }'
  pr-add-review-thread-at: '! gh pr-add-review-thread-gql -F path="$1" -F startLine=$2 -F line=$3 -F body="$4"'
  pr-add-review-thread-suggestion: |
    ! gh pr-add-review-thread-gql -F path="$1" -F startLine=$2 -F line=$3 -F body="\`\`\`suggestion
    $4
    \`\`\`"
  pr-add-review-thread-gql: |
    !
    PR_ID=$(gh pr view ${GH_PR} --json id --jq .id) || exit $?
    gh api graphql -F pullRequestId=$PR_ID -f query='
    mutation($body: String!,
      $pullRequestReviewId: ID,
      $pullRequestId: ID,
      $path: String,
      $line: Int,
      $startLine: Int,
      $side: DiffSide = RIGHT,
      $startSide: DiffSide = RIGHT,
      $subjectType: PullRequestReviewThreadSubjectType = FILE
    ) {
      addPullRequestReviewThread(input: {
        body: $body,
        pullRequestReviewId: $pullRequestReviewId,
        pullRequestId: $pullRequestId,
        path: $path,
        line: $line,
        startLine: $startLine,
        side: $side,
        startSide: $startSide,
        subjectType: $subjectType
      }) {
        thread { id }
        clientMutationId
      }
    }' "$@"
  pr-commit-range: "pr view --json mergeCommit --jq '.mergeCommit.oid + \"^...\" + .mergeCommit.oid + \"^2\"'"
  cherry-pick-pr: |
    !
    if [[ $# -lt 1 ]]; then echo "Specify the PR number"; exit 1; fi;
    MERGE_COMMIT=$(gh pr view --json mergeCommit --jq .mergeCommit.oid $1) &&
      RANGE=$MERGE_COMMIT^...$MERGE_COMMIT^2 &&
      git log --graph --oneline $RANGE &&
      zsh -c "read -q '?> MERGE_COMMIT=\$(gh pr view --json mergeCommit --jq .mergeCommit.oid $1) && git cherry-pick \$MERGE_COMMIT^...\$MERGE_COMMIT^2'$'\\n''Continue? (y/n) '" &&
      git cherry-pick $RANGE
  my-review-requests: |
    pr list --search "sort:updated-desc user-review-requested:@me" --json number,title,url,headRefName,author,createdAt --template '
    {{- tablerow ("ID" | autocolor "+u") ("TITLE" | autocolor "+u") ("BRANCH" | autocolor "+u") ("AUTHOR" | autocolor "+u") ("CREATED AT" | autocolor "+u") }}
    {{- range . }}
      {{- $author := "-" }}
      {{- $authorHref := (print "https://github.com/" .author.login) }}
      {{- if .author.name}}
        {{- $author = .author.name}}
      {{- else if .author.login | hasPrefix "app/"}}
        {{- $author = (slice .author.login 4) }}
        {{- $authorHref = (print "https://github.com/apps/" $author) }}
      {{- else }}
        {{- $author = .author.login}}
      {{- end}}
      {{- tablerow
        (printf "#%v" .number | autocolor "green")
        (hyperlink .url (.title | truncate 70))
        (.headRefName | autocolor "cyan")
        (hyperlink $authorHref $author)
        (.createdAt | timeago | color "magenta")
      }}
    {{- end}}'
  my-latest-review-request: 'pr list --search "sort:updated-desc user-review-requested:@me" --limit 1 --json number --jq .[].number'
  repo-set-remote: '!gh repo set-default $(git remote get-url $1)'
  wfr: '!gh workflow run --ref $(git rev-parse --abbrev-ref --symbolic-full-name @{u} | sd "^[^/]*/" "") "$@"'
  wr: "!GH_RUN=\"$(gh run list --workflow=$1 -L1 --json databaseId,url --template '{{range .}}{{printf \"%.f\" .databaseId}}\n{{.url}}{{break}}{{end}}')\"; echo \"$GH_RUN\" | cut -d'\n' -f2; gh run watch $(echo \"$GH_RUN\" | cut -d'\n' -f1)"
  wfrw: '!gh wfr "$@" && sleep 3 && gh run list --workflow=$1 --limit=3 && sleep 3 && gh wr "$1"'
  prism: '!gh-prism "$@"'
  my-prs: pr list --author '@me'
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
