theme = "thursday"

# theme = "sonokai"
# theme = "tokyonight"

[editor]
line-number = "relative"
# cursorline = true
color-modes = true
insert-final-newline = true
# indent-style = 2
auto-format = false
bufferline = "multiple"

[editor.soft-wrap]
enable=false
wrap-at-text-width = true

[editor.terminal]
command = "it2split"
args = ["--no-focus", "--cwd=%{current_working_directory}"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
ignore = true
git-ignore = true
git-global = true
git-exclude = true

# see 'impl Default for StatusLineConfig' for defaults
[editor.statusline]
center = [
  "version-control",
]
right = [
  # default
  "diagnostics",
  # added
  "file-type",
  "file-indent-style",
  # default
  "selections",
  "register",
  "position",
  "file-encoding",
]

[editor.lsp]
display-messages = true

[editor.inline-diagnostics]
cursor-line = "info"

[keys.normal]
"#" = ":reflow"
# macos new terminal tab
"C-t" = ":sh it2split cd \"%{buffer_name}\""
"C-A-o" = ":sh open '%{selection}'"
"C-y" = ":sh printf '%%s' '%{buffer_name}' | pbcopy"
# "A-[" = "move_prev_sub_word_end"
# "A-]" = "move_next_sub_word_start"
"C-left" = "move_prev_sub_word_start"
"C-right" = "move_next_sub_word_end"
"A-F4" = ":buffer-close"
"A-k" = ":tree-sitter-subtree"
"A-z" = ":toggle-option soft-wrap.enable"
"esc" = [":redraw"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
S-m = "match_brackets"
A-m = "select_textobject_around"

"H" = ["ensure_selections_forward", "collapse_selection", "select_mode", "goto_line_start", "exit_select_mode"]
"L" = ["ensure_selections_forward", "flip_selections", "collapse_selection", "select_mode", "goto_line_end", "exit_select_mode"]

"F2" = "rename_symbol"
"F3" = ":format"

[keys.normal."C-w"]
"c" = ":buffer-close"
"g" = ":cd %sh{dirname %{file_path_absolute}}"
"G" = ":cd %sh{git root}"

[keys.normal.space.w]
"c" = ":buffer-close"

[keys.normal.space]
"e" = "file_explorer_in_current_buffer_directory"
# https://github.com/helix-editor/helix/wiki/Recipes#advanced-file-explorer-with-yazi
"E" = [
  ":sh rm -f /tmp/unique-file-h21a434",
  # ':insert-output lf --selection-path=/tmp/unique-file-h21a434 "%sh{echo %{buffer_name}}"',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file-h21a434',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]
"C-r" = [
  ":write-all",
  # cargo binstall swpui
  # ':insert-output swp "%{selection}" >/dev/tty',
  # ':insert-output serpl "%{selection}" >/dev/tty',
  ':insert-output scooterhx "%{selection}" >/dev/tty',
  # scooterhx:
  # #!/usr/bin/env zsh
  # printf "\x1b[?2004l" > /dev/tty
  # args=()
  # if [[ -n "$1" ]]; then
  #   args+=(--search-text "$1")
  # fi
  # scooter --no-stdin ${args[@]} >/dev/tty
  # code=$?
  # printf "\x1b[?1049h\x1b[?2004h" >/dev/tty
  # exit $code
  ":redraw",
  ":reload-all"
]
"A-e" = "file_explorer"
"C-o" = ":sh open '%{selection}'"
"C-g" = ":sh gh bf '%{buffer_name}' 'L%{selection_line_start}-L%{selection_line_end}'"
"C-G" = ":sh it2split --no-focus git diffd -w ${HELIX_GIT_HEAD:-HEAD} -- '%{buffer_name}'"
"A-x" = ":sh gh pr-file-unqueue '%{buffer_name}'"
"x" = ":sh gh pr-file-viewed '%{buffer_name}'"
"X" = ":sh gh pr-file-unviewed-gql '%{buffer_name}'"
"t" = [
  ":write-all",
  ":sh it2split --no-focus jest '%{buffer_name}'",
]
"-" = ":sh git removed %{cursor_line} ${HELIX_GIT_HEAD:-HEAD} -- %{buffer_name}"
"_" = ":insert-output git removed --insert %{cursor_line} ${HELIX_GIT_HEAD:-HEAD} -- %{buffer_name}"
"C-y" = ":sh /opt/homebrew/opt/coreutils/libexec/gnubin/echo -n '%{buffer_name}:%{cursor_line}' | pbcopy"
"U" = ":sh gh pr-add-review-thread-suggestion %{buffer_name} %{selection_line_start} %{selection_line_end} \"$(pbpaste)\""
"backspace" = ":sh it2split --no-focus yare build"
"Q" = ":buffer-close"

[keys.normal.space.g]
"f" = "changed_file_picker"
"b" = ":sh gh prb"
"a" = ":sh git add %{buffer_name}"
"d" = ":sh it2split --no-focus git diffdh -w ${HELIX_GIT_HEAD:-HEAD} -- '%{buffer_name}'"
"v" = ":sh it2split --no-focus gh pr-unresolved-comments-file '%{buffer_name}'"
"n" = ":open %sh{gh pr-queued-files | head -n1}"
"N" = [
  ":buffer-close-all",
  ":open %sh{gh pr-unread-files | head -n1}",
]
# "n" = ":open %sh{zet diff <(gh pr-unread-files | head -n1) .github/skipped-review-files}"
"i" = ":sh echo '${buffer_name}' >> .github/skipped-review-files"
"l" = ":sh it2split --no-focus git logp --patience -w %{buffer_name}"
"L" = ":sh it2split --no-focus git logd -w -L'%{selection_line_start},%{selection_line_end}:%{buffer_name}'"
"o" = ":sh gh pfh '%{buffer_name}' 'R%{selection_line_start}-R%{selection_line_end}'"
"O" = ":sh gh browse --commit=%sh{git nearest-remote-rev} '%{buffer_name}:%{selection_line_start}'"
"y" = ":sh gh browse --commit=%sh{git nearest-remote-rev} '%{buffer_name}:%{selection_line_start}' --no-browser | pbcopy"
"u" = ":sh it2split --pause gh pr-add-review-thread-at %{buffer_name} %{selection_line_start} %{selection_line_end} \"\""
"U" = ":sh gh pr-add-review-thread-suggestion %{buffer_name} %{selection_line_start} %{selection_line_end} \"$(pbpaste)\""

[keys.normal.z]
"x" = [
  ":toggle-option file-explorer.git-global",
  ":toggle-option file-explorer.git-exclude",
  ":toggle-option file-explorer.git-ignore",
  ":toggle-option file-explorer.ignore",
  # ":toggle-option file-picker.git-ignore",
  # ":toggle-option file-picker.ignore",
]
"." = [
  ":toggle-option file-explorer.hidden",
  ":toggle-option file-picker.hidden"
]
"w" = ":toggle-option soft-wrap.enable"

[keys.normal.g]
"h" = ["collapse_selection", "extend_to_line_start"]
"l" = ["collapse_selection", "extend_to_line_end"]
"s" = ["collapse_selection", "extend_to_first_nonwhitespace"]

"R" = ":open --list %sh{findrelated %{buffer_name}}"
"V" = ":sh wait-code --no-wait -g %{buffer_name}:%{cursor_line}:%{cursor_column}"

[keys.select]
"C-left" = "extend_prev_sub_word_start"
"C-right" = "extend_next_sub_word_end"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.insert]
S-tab = "move_parent_node_start"
"C-space" = "completion"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end_newline"

