theme = "thursday"

# theme = "sonokai"
# theme = "tokyonight"

[editor]
line-number = "relative"
# cursorline = true
color-modes = true
insert-final-newline = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"#" = ":reflow"

[keys.insert]
"C-space" = "completion"

[editor.file-picker]
hidden = false
# git-ignore = false
# git-global = false
git-exclude = false

