[language-server.typescript-language-server]
config.tsserver.path = "node_modules/typescript/lib"
config.preferences.quotePreference = "single"

# see https://github.com/helix-editor/helix/discussions/8452
[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
# format = { enable = true }
nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionsOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" }

[language-server.vscode-json-language-server.config]
provideFormatter = false

[[language]]
name = "json"
auto-format = false
# config = { "provideFormatter" = false, "json" = { "keepLines" = { "enable" = true } } }
# config = { "json" = { "validate" = { "enable" = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "git-commit"
file-types = [{ glob = "COMMIT_EDITMSG" }, { glob = "MERGE_MSG" }, { glob = "COMMIT_EDITMSG-*.txt" }]
