[language-server.hx-lsp]
command = "hx-lsp"

[language-server.nxls]
command = "nxls"
args = ["--stdio"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
python.analysis.venvPath = "."
python.analysis.venv = ".venv"
python.analysis.lint = true
python.analysis.inlayHint.enable = true
python.analysis.autoSearchPaths = true
python.analysis.diagnosticMode = "workspace"
python.analysis.useLibraryCodeForType = true
python.analysis.logLevel = "Error"
python.analysis.typeCheckingMode = "off"
python.analysis.autoImoprtCompletion = true
python.analysis.reportOptionalSubscript = false
python.analysis.reportOptionalMemberAccess = false

[language-server.efm]
command = "efm-langserver"

[language-server.efm-lsp-eslint]
command = "efm-langserver"

[language-server.efm-lsp-eslint.config]
documentFormatting = true

[[language-server.efm-lsp-eslint.config.languages.typescript]]
# formatCommand ="eslint --stdin-filename ${INPUT}"
# formatStdin = true
lintCommand = "npx eslint -f visualstudio --stdin --stdin-filename ${INPUT}"
lintIgnoreExitCode = true
lintStdin = true
lintFormats = [
  "%f(%l,%c): %tarning %m",
  "%f(%l,%c): %rror %m",
]

[language-server.typescript-language-server]
config.tsserver.path = "node_modules/typescript/lib"
config.preferences.quotePreference = "single"
config.diagnostics.ignoredCodes = [
  80001, # File is a CommonJS module; it may be converted to an ES module
]

[language-server.typescript-language-server.config.typescript]
implementationsCodeLens.enabled = true
referencesCodeLens.enabled = true
referencesCodeLens.showOnAllFunctions = true

[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true

[language-server.tsgo]
command = "tsgo"
args = ["lsp", "--stdio"]

[language-server.tsgo.config.typescript]
preferences.quotePreference = "single"
diagnostics.ignoredCodes = [
  80001, # File is a CommonJS module; it may be converted to an ES module
]
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes = true
inlayHints.enumMemberValues.enabled = true
suggest.completeFunctionCalls = true
tsserver.path = "node_modules/typescript/lib"
# tsserver.enableTracing = true
updateImportsOnFileMove = { enabled = "always" }

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.vtsls.config.typescript]
preferences.quotePreference = "single"
diagnostics.ignoredCodes = [
  80001, # File is a CommonJS module; it may be converted to an ES module
]
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes = true
inlayHints.enumMemberValues.enabled = true
suggest.completeFunctionCalls = true
tsserver.path = "node_modules/typescript/lib"
# tsserver.enableTracing = true
updateImportsOnFileMove = { enabled = "always" }

# see https://github.com/helix-editor/helix/discussions/8452
[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"
# command = "node"
# args = [
#   "--optimize-for-size",
#   "--max-old-space-size=8192",
#   "$HOME/code/public/vscode-langservers-extracted/lib/eslint-language-server/eslintServer.js",
#   # "/opt/homebrew/lib/node_modules/vscode-langservers-extracted/lib/eslint-language-server/eslintServer.js",
#   "--stdio",
# ]

[language-server.eslint.config]
validate = "on"
# format = { enable = true }
nodePath = ""
execArgv = [ "--optimize-for-size", "--max-old-space-size=8192" ]
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onSave"
# useESLintClass = false
# codeActionsOnSave = { mode = "all" }
experimental = { useFlatConfig = false }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[language-server.eslint.config.codeAction]
[language-server.eslint.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.eslint.config.codeAction.showDocumentation]
enable = true

[language-server.eslint.config.codeActionOnSave]
enable = false
mode = "fixAll"

[language-server.vscode-json-language-server.config]
provideFormatter = false

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["tsconfig.json", "tsconfig.*.json"]
url = "https://json.schemastore.org/tsconfig.json"

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = [ "package.json" ]
url = "https://json.schemastore.org/package.json"

[language-server.commit-lsp]
command = "commit-lsp"
args = ["run"]

[language-server.cci-yaml]
command = "$HOME/Library/Application Support/CircleCI-language-server/circleci-yaml-language-server"
args = ["-schema=$HOME/Library/Application Support/CircleCI-language-server/schema.json", "--stdio"]

[[grammar]]
name = "angular"
# source = { git = "https://github.com/dlvandenberg/tree-sitter-angular", rev = "d1f24a8890462cb740909ff62a3a079cded288bc" }
source = { git = "https://github.com/forivall/tree-sitter-angular", rev = "df5d783d9afb45566afa03db129190253b46771b" }

[[grammar]]
name = "zsh"
source = { git = "https://github.com/lincheney/tree-sitter-zsh", rev = "8fb08cf93c40ffd8c97b1b0d491b5f91bf1aab47" }

[[language]]
name = "angular"
scope = "source.angular"
injection-regex = "html"
file-types = ["component.html"]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = [ "angular" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'npx', args = ["prettier", "--parser", "angular"] }

[[language]]
name = "nxjson"
grammar = "json"
scope = "source.json"
file-types = [
  { "glob" = "nx.json" },
  { "glob" = "project.json" },
]
language-servers = [ "vscode-json-language-server", "nxls" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
auto-format = false
# config = { "provideFormatter" = false, "json" = { "keepLines" = { "enable" = true } } }
# config = { "json" = { "validate" = { "enable" = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "git-commit"
file-types = [{ glob = "COMMIT_EDITMSG" }, { glob = "MERGE_MSG" }, { glob = "COMMIT_EDITMSG-*.txt" }]
language-servers = [ "commit-lsp" ]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "babel"] }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "angular"] }

[[language]]
name = "javascript"
language-servers = [
  # { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "vtsls", except-features = ["format"] },
  # { name = "tsgo", except-features = ["format"] },
  # { name = "graphql-language-service", except-features = [ "format" ] },
  "eslint",
]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  # { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "vtsls", except-features = ["format"] },
  # { name = "tsgo", except-features = ["format"] },
  # { name = "efm", "only-features" = [ "diagnostics", "format",  ] },
  # { name = "efm-lsp-eslint" },
  { name = "graphql-language-service", except-features = [ "format" ] },
  "eslint",
]

[[language]]
name = "toml"
language-servers = [
  # "taplo",
  "tombi",
]

[[language]]
name = "ruby"
auto-format = false

# [[language]]
# name = "angular"
# scope = "source.angular"
# roots = ["angular.json", "nx.json"]
# language-server = { command = "ngserver", args = ["--stdio", "--tsProbeLocations", "$(npm -g root)", "--ngProbeLocations", "$(npm -g root)"] }
# file-types = ["ts", "html"]
[[language]]
name = "yaml"
language-servers = [ "yaml-language-server", "ansible-language-server" ]

[[language]]
name = "yaml-cci"
grammar = "yaml"
scope = "source.yaml"
file-types = [
  { glob = ".circleci/config.yml" },
]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "yaml-language-server", "cci-yaml" ]
formatter = { command = "yamlfmt", args = ['-'] }
auto-format = true

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "hx-lsp" ]

[[language]]
name = "zsh"
scope = "source.zsh"
injection-regex = "zsh"
file-types = [
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "zsh-theme",
  "zshrc_Apple_Terminal",
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = ".zshrc" },
  { glob = ".zimrc" },
]
shebangs = ["zsh"]
comment-token = "#"
language-servers = [ "bash-language-server" ]
indent = { tab-width = 2, unit = "  " }
