[language-server.typescript-language-server]
config.tsserver.path = "node_modules/typescript/lib"
config.preferences.quotePreference = "single"
config.diagnostics.ignoredCodes = [
  80001, # File is a CommonJS module; it may be converted to an ES module
]

[language-server.typescript-language-server.config.typescript]
implementationsCodeLens.enabled = true
referencesCodeLens.enabled = true
referencesCodeLens.showOnAllFunctions = true

[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true

# see https://github.com/helix-editor/helix/discussions/8452
[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
validate = "on"
# format = { enable = true }
nodePath = ""
execArgv = [ "--optimize-for-size", "--max-old-space-size=8192" ]
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onSave"
# useESLintClass = false
# codeActionsOnSave = { mode = "all" }
experimental = { useFlatConfig = false }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[language-server.eslint.config.codeAction]
[language-server.eslint.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.eslint.config.codeAction.showDocumentation]
enable = true

[language-server.eslint.config.codeActionOnSave]
enable = false
mode = "fixAll"

[language-server.vscode-json-language-server.config]
provideFormatter = false

[language-server.commit-lsp]
command = "commit-lsp"
args = ["run"]

[[language]]
name = "json"
auto-format = false
# config = { "provideFormatter" = false, "json" = { "keepLines" = { "enable" = true } } }
# config = { "json" = { "validate" = { "enable" = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "git-commit"
file-types = [{ glob = "COMMIT_EDITMSG" }, { glob = "MERGE_MSG" }, { glob = "COMMIT_EDITMSG-*.txt" }]
language-servers = [ "commit-lsp" ]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "angular"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "eslint",
]

[[language]]
name = "ruby"
auto-format = false

# [[language]]
# name = "angular"
# scope = "source.angular"
# roots = ["angular.json", "nx.json"]
# language-server = { command = "ngserver", args = ["--stdio", "--tsProbeLocations", "$(npm -g root)", "--ngProbeLocations", "$(npm -g root)"] }
# file-types = ["ts", "html"]
