# basic .paneru.toml
[options]
focus_follows_mouse = false
mouse_follows_focus = false
# animation_speed = 32
animation_speed = 16
preset_column_widths = [
  0.2,
  0.2333,
  0.2667,
  0.3,
  0.3333,
  0.3667,
  0.4,
  0.4333,
  0.4667,
  0.5,
  0.5333,
  0.5667,
  0.6,
  0.6333,
  0.6667,
  0.7,
  0.7333,
  0.7667,
  0.8,
  0.8333,
  0.8667,
  0.9,
  0.9333,
  0.9667,
]

[bindings]
window_focus_west = "cmd + alt + ctrl - h"
window_focus_east = "cmd + alt + ctrl- l"
window_focus_south = "cmd + alt + ctrl - j"
window_focus_north = "cmd + alt + ctrl - k"
window_swap_west = "cmd + alt + shift + ctrl - h"
window_swap_east = "cmd + alt + shift + ctrl - l"
window_grow = "cmd + alt - f12"
window_shrink = "cmd + alt - f11"
window_manage = "cmd + alt - f9"
# window_resize = "alt - r"
window_center = "cmd + alt - f10"
window_stack = "cmd + shift - k"
window_unstack = "cmd + shift - j"
quit = "ctrl + alt - q"

# [padding]
# left = 75

[swipe]
sensitivity = 0.3
[swipe.gesture]
fingers_count = 3

[swipe.scroll]
modifier = "alt + cmd"
