#!/usr/bin/env zsh

# TODO: change to zplug

# prebuild global commands for zsh-nvm lazy loading plugin
__zsh_yargs_plugin__build_completions() {
  unset NVM_LAZY_LOAD_GLOBAL_COMMANDS
  (echo "export NVM_LAZY_LOAD_GLOBAL_COMMANDS=("
  _zsh_nvm_global_binaries
  echo ")") > "${__zsh_nvm_plugin__dirname}/cache"
}
