#!/usr/bin/env zsh

set -eo pipefail

args=($1)
if [[ $1 == --*\ * ]]; then
  args=(${1%% *} ${1#--* })
fi

showarg=${args[1]}
if [[ $1 == '--show-current' ]] || [[ $1 == '--describe' ]]; then
  cd $2
  print -P '%~'
else
  args=(--list $args)
fi

if [[ $1 == '--describe' ]]; then
  branch=${$(git describe --all)#heads/}
  if [[ $branch != tags/* ]]; then
    git -c color.branch=always branch -vvv --list ${$(git describe --all)#heads/}
  else
    autoload colors && colors
    echo ${fg[yellow]}$branch${fg[reset]}
  fi
else
  git -c color.branch=always branch -vvv ${args[@]}
fi
if [[ $showarg == --remotes ]]; then
  showarg=${args[2]}
elif [[ $showarg == --show-current ]] || [[ $showarg == '--describe' ]]; then
  showarg=HEAD
fi

git show --color=always --no-patch --pretty="format:%C(magenta)♘ %an <%ae>%Creset%n%C(blue)✍ %aD%C(reset) %C(cyan)♔ %cD%Creset%n" "${showarg[@]}"
