#!/usr/bin/env zsh

set -eo pipefail

args=($1)
if [[ $1 == --*\ * ]]; then
  args=(${1%% *} ${1#--* })
fi

git -c color.branch=always branch --list -vvv ${args[@]}
showarg=${args[1]}
if [[ $showarg == --remotes ]]; then
  showarg=${args[2]}
fi

git show --color=always --no-patch --pretty="format:%C(magenta)♘ %an <%ae>%Creset%n%C(blue)✍ %aD%C(reset) %C(cyan)♔ %cD%Creset%n" $showarg
