#!/usr/bin/env zsh
# code: language=shellscript

__git-patch-filepicker() {
  # if [[ -v configArgs ]]; then
  #   if (( ${+commands[dark-mode]} )) && [[ $(dark-mode status) == off ]]; then
  #     configArgs+=(-c interactive.diffFilter="$(command git config interactive.diffFilter) --light --syntax-theme ${DELTA_LIGHT_THEME:-GitHub}")
  #   fi
  # fi
  hasfiles=$1
  shift
  getitems=$1
  shift
  dointeractive=$1
  shift

  local items=()
  local term_menu_options

  cdup=$(git rev-parse --show-cdup)
  local first=true
  local usecdup
  while $hasfiles "$@"; do
    usecdup=true
    term_menu_options=()
    # git diff --name-only | selecta --height 4 | read file
    if [[ $getitems = *_vars ]]; then
      $getitems "$@"
    else
      local OIFS=$IFS
      IFS=$'\n'
      items=($($getitems "$@"))
      IFS="$OIFS"
    fi
    if $first && (( ${#items} == 1 )); then
      i=1

    else
      # $ python3 -m pip install simple-term-menu

      simple-term-menu -i $(( i - 1 )) $term_menu_options "${items[@]}" && i=0 || i=$?
      if (( $i == 0 )) ; then return 1; fi
    fi
    file=${items[i]}
    items=()
    interactiveArg=$file
    if $usecdup; then
      interactiveArg=$cdup$file
    fi
    $dointeractive $interactiveArg
    first=false
  done
}

__git-patch-filepicker "$@"
