#!/usr/bin/env zsh

set -eo pipefail

autoload colors && colors

echo ---

show_lines=("${(f)$(git show --format='' --raw --numstat --summary --follow $@)}")
rawstat=($(echo ${show_lines[1]}))
numstat=($(echo ${show_lines[2]}))
summary=($(echo ${show_lines[3]}))
added=${numstat[1]}
removed=${numstat[2]}
  if [[ "$diffstat" = C* ]]; then
    intro="${fg[cyan]}Copied${reset_color} from ${fg[yellow]}${rawstat[6]}${reset_color} ${summary[5]}"
  elif [[ "$diffstat" = R* ]]; then
    intro="${fg[cyan]}Renamed${reset_color} from ${fg[yellow]}${rawstat[6]}${reset_color} ${summary[5]}"
  elif [[ "$diffstat" = D ]]; then
    intro="${fg[cyan]}Deleted${reset_color}"
  elif [[ "$diffstat" = A ]]; then
    intro="${fg[cyan]}Added${reset_color} new"
  else
    intro="${fg[cyan]}Changed${reset_color}"
  fi

  [[ "$diffstat" != A ]] && (( removed == 0 && added == 0 )) && wsonly=true || wsonly=false
  if $wsonly; then
    numstat=($(git diff --numstat --follow -- $1))
    added=${numstat[1]}
    removed=${numstat[2]}
  fi
  if (( removed > 0 || added > 0 )); then
    case "$diffstat" in A) lineinfo+=" file";& C*|R*|D) lineinfo+=" with";; esac
    if (( added > 0 )); then
      lineinfo+=" $added new"
      if (( removed > 0 )); then
        lineinfo+=","
      fi
    fi
    if (( removed > 0 )); then
      lineinfo+=" $removed removed"
    fi
    lineinfo+=" line"
    if (( removed == 1 && added > 1 )); then
      lineinfo+="(s)"
    elif (( removed > 1 || added > 1 )); then
      lineinfo+="s"
    fi
  elif [[ "$diffstat" = A ]]; then
    lineinfo+=" empty file"
  fi
  if $wsonly; then
    lineinfo+=" (whitespace only)"
  fi
  echo "$intro$lineinfo"

  total=$(( added + removed ))
  totallen=${#total}
  STAT_COLUMNS=$(( COLUMNS - totallen - 1 ))
  if $(( total > STAT_COLUMNS )); then
    added=$(( STAT_COLUMNS * added / total ))
    removed=$(( STAT_COLUMNS * added / total ))
  fi
  echo $total ${fg[green]}${(l:${added}::+:)}${fg[red]}${(l:${removed}::-:)}${reset_color}
else
  if [[ "${rawstat[5]}" = C* ]]; then
    echo "${fg[cyan]}Copied${reset_color} from ${fg[yellow]}${rawstat[6]}${reset_color} ${summary[5]}"
  elif [[ "${rawstat[5]}" = R* ]]; then
    echo "${fg[cyan]}Renamed${reset_color} from ${fg[yellow]}${rawstat[6]}${reset_color} ${summary[5]}"
  else
    echo "${fg[cyan]}Created empty file${reset_color}"
  fi
fi

#  $@ | delta

