#!/usr/bin/env zsh
# code: language=shellscript

PICKER_BACKEND=fzf

__simple-term-picker() {
  # $ python3 -m pip install simple-term-menu

  local term_menu_options=()
  if "${TERM_PICKER_MULTI:-false}"; then
    term_menu_options+=(-m)
  fi
  if [[ -n "$TERM_PICKER_PREVIEW_COMMAND" ]]; then
    term_menu_options+=(--preview "$TERM_PICKER_PREVIEW_COMMAND")
  fi
  if "${TERM_PICKER_MULTI:-false}" || (( ${#items} > 255 )); then
    i=$(simple-term-menu --stdout -i $(( i - 1 )) --no-preview-border $term_menu_options "${items[@]}") || true
    [[ -z $i ]] && i=0
  else
    simple-term-menu -i $(( i - 1 )) --no-preview-border $term_menu_options "${items[@]}" && i=0 || i=$?
  fi
}

if [[ $PICKER_BACKEND == fzf ]]; then
  __simple-term-picker() {
    local fzf_options=()
    if "${TERM_PICKER_MULTI:-false}"; then
      fzf_options+=(-m)
    fi
    local heightpct=80
    if [[ -n "$TERM_PICKER_PREVIEW_COMMAND" ]]; then
      local itemcount=${#items}
      local previewlines=$(( LINES*heightpct/100 - itemcount - 1 ))
      if (( previewlines < 5 )); then
        previewlines=5
      fi
      if (( previewlines > LINES )); then
        previewlines=$((LINES - 3))
        if (( previewlines < 2 )); then
          previewlines=2
        fi
      fi
      fzf_options+=(--preview "$TERM_PICKER_PREVIEW_COMMAND" --layout=reverse --preview-window=down,$previewlines,nohidden)
    fi
    local fzf_output="$(printf "%s\n" ${items[@]} | fzf "${fzf_options[@]}" \
      --ansi --cycle --disabled --accept-nth='{n}' --height=${heightpct}% \
      --prompt '> ' \
      --bind "load:pos($i)" \
      --bind 'j:down,k:up,g:first,G:last,d:half-page-down,u:half-page-up,q:abort' \
      --bind '/:enable-search+unbind(j,k,g,G,d,u,q)+change-prompt(~ )' \
      --bind 'esc:transform:[[ $FZF_PROMPT == "~ " ]] && echo "disable-search+rebind(j,k,g,G,d,u,q)+change-prompt(> )+clear-query" || echo "abort"'
    )"
    if [[ -z $fzf_output ]]; then i=0; else
      local fzf_items=(${(f)fzf_output})
      for j in {1..${#fzf_items}}; do (( ++fzf_items[j] )); done
      i="${(j:,:)fzf_items}"
    fi
  }
fi

__git-patch-filepicker() {
  # if [[ -v configArgs ]]; then
  #   if (( ${+commands[dark-mode]} )) && [[ $(dark-mode status) == off ]]; then
  #     configArgs+=(-c interactive.diffFilter="$(command git config interactive.diffFilter) --light --syntax-theme ${DELTA_LIGHT_THEME:-GitHub}")
  #   fi
  # fi
  hasfiles=$1
  shift
  getitems=$1
  shift
  dointeractive=$1
  shift

  local items=()
  local term_menu_options

  cdup=$(git rev-parse --show-cdup)
  local first=true
  local usecdup interactiveArg
  typeset -a interactiveArgs
  while $hasfiles "$@"; do
    usecdup=true
    term_menu_options=()
    if [[ $getitems = *_vars ]]; then
      $getitems "$@"
    else
      local OIFS=$IFS
      IFS=$'\n'
      items=($($getitems "$@"))
      IFS="$OIFS"
    fi
    if $first && (( ${#items} == 1 )); then
      i=1
    else
      __simple-term-picker
      if (( $i == 0 )) ; then return 1; fi
    fi
    interactiveArgs=()
    if "${TERM_PICKER_MULTI:-false}"; then
      for j in ${(s/,/)i}; do
        file="${items[j]}"
        interactiveArg=$file
        if $usecdup; then
          interactiveArg=$cdup$file
        fi
        interactiveArgs+=($interactiveArg)
      done
    else
      file=${items[i]}
      interactiveArg=$file
      if $usecdup; then
        interactiveArg=$cdup$file
      fi
      interactiveArgs+=($interactiveArg)
    fi
    items=()
    $dointeractive "${interactiveArgs[@]}"
    first=false
  done
  unset TERM_PICKER_MULTI
  unset TERM_PICKER_PREVIEW_COMMAND
}

__git-patch-filepicker "$@"
