#!/usr/bin/env zsh

__funcinfo=$(whence -v $0 2>&1)
__filename=${__funcinfo#$0 is a shell function from }
__dirname=${__filename:h}

OPTS_SPEC="\
npm show-recent-versions [<options>] <args>...
--
n,count=    show this many versions [default=10]
"
eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt --stuck-long -- "$@" || echo exit $?)"

NUM=10
index=0
for arg in $@; do
  index=$((index+1))
  case "$arg" in
    --count=*) NUM="${arg#--count=}" ;;
    --) break; ;;
  esac
done
args=${@:$((index+1))}

npm show $args --json | jq -L ${__dirname:h:h}/jq 'include "fromjsdate";
.time | to_entries | sort_by(.value | fromjsdate) | .[-'"$NUM"':] | from_entries'
