#!/usr/bin/env zsh

set -G # nullglob

local files=()
# for f in {src,lib,test}/**/*.{js,d.ts}; do
for f in $(git ls-files -o -x 'node_modules' -x coverage -x dist '*.js' '*.d.ts'); do
  if [[ -e ${${f%.*}%.d}.ts ]] files+=($f)
done

if (( ${#files} > 0 )) ; then
  echo trash $files
  trash $files
fi
