# Monokai copy — exported from Canario
[colors]
background           = '#0C0C0C'
foreground           = '#D9D9D9'
cursor               = '#FC971F'
selection-background = '#343434'
selection-foreground = '#FFFFFF'
black                = '#1A1A1A'
red                  = '#F4005F'
green                = '#98E024'
yellow               = '#FD971F'
blue                 = '#9D65FF'
magenta              = '#F4005F'
cyan                 = '#58D1EB'
white                = '#C4C5B5'
light-black          = '#625E4C'
light-red            = '#F4005F'
light-green          = '#98E024'
light-yellow         = '#E0D561'
light-blue           = '#9D65FF'
light-magenta        = '#F4005F'
light-cyan           = '#58D1EB'
light-white          = '#F6F6EF'
