# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: moor
description: Shows file contents. Compressed files will be transparently decompressed.
flags:
  --colors=: 'Highlighting palette size: 8, 16, 256, 16M, auto'
  --debug: Print debug logs after exiting
  --follow: Follow piped input just like "tail -f"
  --lang=: File contents, used for highlighting. Mime type or file extension ("html"). Default is to guess by filename.
  --mousemode=: 'Mouse mode: auto, select or scroll: https://github.com/walles/moor/blob/master/MOUSE.md'
  --no-clear-on-exit: Retain screen contents when exiting moor
  --no-clear-on-exit-margin=: Number of lines to leave for your shell prompt, defaults to 1
  --no-linenumbers: Hide line numbers on startup, press left arrow key to show
  --no-reformat: No effect, kept for compatibility. See --reformat
  --no-search-line-highlight: Do not highlight the background of lines with search hits
  --no-statusbar: Hide the status bar, toggle with '='
  --quit-if-one-screen: Don't page if contents fits on one screen. Affected by --no-clear-on-exit-margin.
  --reformat: Reformat some input files (JSON)
  --render-unprintable=: 'How unprintable characters are rendered: highlight or whitespace'
  --scroll-left-hint=: Shown when view can scroll left. One character with optional ANSI highlighting.
  --scroll-right-hint=: Shown when view can scroll right. One character with optional ANSI highlighting.
  --shift=: Horizontal scroll amount >=1, defaults to 16
  --statusbar=: 'Status bar style: inverse, plain or bold'
  --style=: 'Highlighting style from https://xyproto.github.io/splash/docs/longer/all.html'
  --tab-size=: Number of spaces per tab stop, defaults to 8
  --terminal-fg: Use terminal foreground color rather than style foreground for plain text
  --trace: Print trace logs after exiting
  --version: Prints the moor version number
  --wrap: Wrap long lines
completion:
  flag:
    colors: ["8", "16", "256", "16M", "auto"]
    mousemode: ["auto", "select", "scroll"]
    render-unprintable: ["highlight", "whitespace"]
    statusbar: ["inverse", "plain", "bold"]
  positionalany: ["$files"]
