#!/usr/bin/env zsh
set -e

# https://github.com/kgryte/npm-repo-url

cmd=(pkgrepo "$1" --format=json)
if ! hash pkgrepo 2> /dev/null ; then
  cmd=(npx -p npm-repo-url $cmd)
fi

echo $cmd
pkg="$($cmd|jq -r ".\"$1\"")"
echo "$pkg"
git clone "$pkg"
