#!/usr/bin/env zsh

__zsh_lab_plugin__build_completions() {
  local compfile="${__zsh_lab_plugin__dirname}/_lab"
  echo "Generating completion for lab..." >&2
  lab completion zsh > $compfile
  [[ -f "${ZGEN_INIT}" ]] && echo 'You should run `zgen reset` to ensure that zcompdump get rebuilt'
}
